name: calaroiscount
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  oauth1: ^2.1.0
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.3
  curved_navigation_bar: ^1.0.6
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # التأكد من وجود الصور داخل مجلد "assets/images/"

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          weight: 700
